package dev.provenance.probe;

public enum EventType {
  PROBE_LOADED,
  SERVER_LOADED,
  SERVER_READY,
  SERVER_STOPPED,
  METADATA_INSPECTION,
  METADATA_SUGGESTION,
  PLUGIN_STATE,
  LIFECYCLE_EXCEPTION,
  CLASSIFICATION,
  TARGET_REQUIREMENT,
  STABILIZATION_STARTED,
  STABILIZATION_COMPLETED,
  TEST_PLAN,
  COMMAND_REGISTRATION,
  COMMAND_EXECUTION_STARTED,
  COMMAND_EXECUTION_COMPLETED,
  COMMAND_TIMEOUT,
  COMMAND_OUTPUT,
  COMMAND_ASSERTION,
  COMMAND_TEST_COMPLETED,
  CLEAN_SHUTDOWN_REQUESTED
}
